from bs4 import Tag

from html2bbcode import parse_children_in_node


class MessageProcessor(object):
    """
        Interface for all kinds of message processor

        Every specialized class should implement the process_message method
        that reads a message and does some work on it

        The message is a HTML node as generated by beautiful soup that
        contains the table entry of the post
    """

    def process_message(self, post_id: str, message: Tag):
        raise NotImplementedError("Should have implemented this")


class MessageHTMLToText(MessageProcessor):

    def process_message(self, post_id: str, message: Tag):
        return message.prettify(formatter="minimal")


class MessageHTMLToBBCode(MessageProcessor):

    def process_message(self, post_id: str, message: Tag):
        return parse_children_in_node(message)
